import { Theme } from './types';

export const defaultTheme = (
  defaults = {
    fontFamily: '"Poppins", sans-serif',
  }
): Theme => {
  const { fontFamily } = defaults || {};

  return {
    breakpoints: {
      xs: 0,
      sm: 600,
      md: 960,
      lg: 1280,
      xl: 1920,
    },
    palette: {
      achromatic: {
        black: '#000000',
        white: '#ffffff',
      },
      primary: {
        main: '#5755FF',
        light: '#7A78FF',
        dark: '#2826C0',
        lighter: '#d5d2fe',
        lightest: '#f4f3ff',
        contrastText: '#fff',
      },
      secondary: {
        main: '#ff8f6b',
        light: '#ffb097',
        dark: '#dd9680',
        lighter: '#fee9e1',
        lightest: '#fff3f0',
        contrastText: '#fff',
      },
      success: {
        main: '#51cc56',
        light: '#81c784',
        dark: '#388e3c',
        contrastText: '#fff',
      },
      error: {
        main: '#ff5555',
        light: '#e57373',
        dark: '#d84545',
        contrastText: '#fff',
      },
      warning: {
        main: '#feb63d',
        light: '#fecc76',
        dark: '#f57c00',
        contrastText: '#fff',
      },
      info: {
        main: '#5b93fe',
        light: '#7eaafc',
        dark: '#4e80db',
        contrastText: '#fff',
      },
      greyscale: {
        100: '#dddedf',
        200: '#cfd1d3',
        300: '#c1c4c9',
        400: '#b3b7bd',
        500: '#a6abb2',
        600: '#999fa7',
        700: '#8c939c',
        800: '#7d8591',
        900: '#707986',
      },
    },
    spacing: {
      4: '4px',
      8: '8px',
      16: '16px',
      24: '24px',
      32: '32px',
      40: '40px',
      48: '48px',
      64: '64px',
      76: '76px',
    },
    typography: {
      'caption-small-regular': {
        fontFamily,
        fontWeight: 400,
        fontSize: '10px',
        lineHeight: '1.5',
      },
      'caption-small-medium': {
        fontFamily,
        fontWeight: 500,
        fontSize: '10px',
        lineHeight: '1.5',
      },
      'caption-small-semibold': {
        fontFamily,
        fontWeight: 600,
        fontSize: '10px',
        lineHeight: '1.5',
      },
      'caption-small-bold': {
        fontFamily,
        fontWeight: 700,
        fontSize: '10px',
        lineHeight: '1.5',
      },
      'caption-medium-regular': {
        fontFamily,
        fontWeight: 400,
        fontSize: '11px',
        lineHeight: '1.5',
      },
      'caption-medium-medium': {
        fontFamily,
        fontWeight: 400,
        fontSize: '11px',
        lineHeight: '1.5',
      },
      'caption-medium-semibold': {
        fontFamily,
        fontWeight: 600,
        fontSize: '11px',
        lineHeight: '1.5',
      },
      'caption-medium-bold': {
        fontFamily,
        fontWeight: 700,
        fontSize: '11px',
        lineHeight: '1.5',
      },
      'caption-large-regular': {
        fontFamily,
        fontWeight: 400,
        fontSize: '12px',
        lineHeight: '1.5',
      },
      'caption-large-medium': {
        fontFamily,
        fontWeight: 500,
        fontSize: '12px',
        lineHeight: '1.5',
      },
      'caption-large-semibold': {
        fontFamily,
        fontWeight: 600,
        fontSize: '12px',
        lineHeight: '1.5',
      },
      'caption-large-bold': {
        fontFamily,
        fontWeight: 700,
        fontSize: '12px',
        lineHeight: '1.5',
      },
      'body-small-regular': {
        fontFamily,
        fontWeight: 400,
        fontSize: '14px',
        lineHeight: '1.5',
      },
      'body-small-medium': {
        fontFamily,
        fontWeight: 500,
        fontSize: '14px',
        lineHeight: '1.5',
      },
      'body-small-semibold': {
        fontFamily,
        fontWeight: 600,
        fontSize: '14px',
        lineHeight: '1.5',
      },
      'body-small-bold': {
        fontFamily,
        fontWeight: 700,
        fontSize: '14px',
        lineHeight: '1.5',
      },
      'body-medium-regular': {
        fontFamily,
        fontWeight: 400,
        fontSize: '16px',
        lineHeight: '1.5',
      },
      'body-medium-medium': {
        fontFamily,
        fontWeight: 500,
        fontSize: '16px',
        lineHeight: '1.5',
      },
      'body-medium-semibold': {
        fontFamily,
        fontWeight: 600,
        fontSize: '16px',
        lineHeight: '1.5',
      },
      'body-medium-bold': {
        fontFamily,
        fontWeight: 700,
        fontSize: '16px',
        lineHeight: '1.5',
      },
      'body-large-regular': {
        fontFamily,
        fontWeight: 400,
        fontSize: '20px',
        lineHeight: '1.5',
      },
      'body-large-medium': {
        fontFamily,
        fontWeight: 500,
        fontSize: '20px',
        lineHeight: '1.5',
      },
      'body-large-semibold': {
        fontFamily,
        fontWeight: 600,
        fontSize: '20px',
        lineHeight: '1.5',
      },
      'body-large-bold': {
        fontFamily,
        fontWeight: 700,
        fontSize: '20px',
        lineHeight: '1.5',
      },
      'display-small-regular': {
        fontFamily,
        fontWeight: 400,
        fontSize: '24px',
        lineHeight: '1.5',
      },
      'display-small-medium': {
        fontFamily,
        fontWeight: 500,
        fontSize: '24px',
        lineHeight: '1.5',
      },
      'display-small-semibold': {
        fontFamily,
        fontWeight: 600,
        fontSize: '24px',
        lineHeight: '1.5',
      },
      'display-small-bold': {
        fontFamily,
        fontWeight: 700,
        fontSize: '24px',
        lineHeight: '1.5',
      },
      'display-medium-regular': {
        fontFamily,
        fontWeight: 400,
        fontSize: '32px',
        lineHeight: '1.5',
      },
      'display-medium-medium': {
        fontFamily,
        fontWeight: 500,
        fontSize: '32px',
        lineHeight: '1.5',
      },
      'display-medium-semibold': {
        fontFamily,
        fontWeight: 600,
        fontSize: '32px',
        lineHeight: '1.5',
      },
      'display-medium-bold': {
        fontFamily,
        fontWeight: 700,
        fontSize: '32px',
        lineHeight: '1.5',
      },
      'display-large-regular': {
        fontFamily,
        fontWeight: 400,
        fontSize: '40px',
        lineHeight: '1.5',
      },
      'display-large-medium': {
        fontFamily,
        fontWeight: 500,
        fontSize: '40px',
        lineHeight: '1.5',
      },
      'display-large-semibold': {
        fontFamily,
        fontWeight: 600,
        fontSize: '40px',
        lineHeight: '1.5',
      },
      'display-large-bold': {
        fontFamily,
        fontWeight: 700,
        fontSize: '40px',
        lineHeight: '1.5',
      },
    },
    shadow: {
      1: '0px 1px 3px rgba(0, 0, 0, 0.12), 0px 1px 2px rgba(0, 0, 0, 0.24)',
      2: '0px 3px 6px rgba(0, 0, 0, 0.16), 0px 3px 6px rgba(0, 0, 0, 0.23)',
      3: '0px 10px 20px rgba(0, 0, 0, 0.19), 0px 6px 6px rgba(0, 0, 0, 0.23)',
      4: '0px 14px 28px rgba(0, 0, 0, 0.25), 0px 10px 10px rgba(0, 0, 0, 0.22)',
      5: '0px 19px 38px rgba(0, 0, 0, 0.30), 0px 15px 12px rgba(0, 0, 0, 0.22)',
    },
  };
};
